services:
  iotFrontendBuild:
    image: node:22.4.0
    container_name: iotFrontend
    ports:
      - "${SERVICE_PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run build && node server.js"
    networks:
        - iot-net
    restart: always

networks:
  iot-net:
    external: true