export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const ADMIN_REGISTRATION = "ADMIN_REGISTRATION";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_EMAIL_NOTIFICATIONS_SUCCESS = "GET_EMAIL_NOTIFICATIONS_SUCCESS";
export const GET_EMAIL_NOTIFICATIONS_FAIL = "GET_EMAIL_NOTIFICATIONS_FAIL";
export const GET_POPUP_NOTIFICATIONS_SUCCESS = "GET_POPUP_NOTIFICATIONS_SUCCESS";
export const GET_POPUP_NOTIFICATIONS_FAIL = "GET_POPUP_NOTIFICATIONS_FAIL";

export const GET_ENABLED_PROFILES_SUCCESS = "GET_ENABLED_PROFILES_SUCCESS";
export const GET_DISABLED_PROFILES_SUCCESS = "GET_DISABLED_PROFILES_SUCCESS";

export const GET_MACHINES_SUCCESS = "GET_MACHINES_SUCCESS";
export const GET_MACHINES_FAIL = "GET_MACHINES_FAIL";